/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Mendes
 */
public class frm_Load extends javax.swing.JFrame {

    /**
     * Creates new form frm_load
     */
    public frm_Load() {
        initComponents();
        btn_ir.setVisible(false);
        
        new Thread(){
        
        public void run(){
            for(int i = 0; i<101; i++){
                try { 
                    sleep(60);
                    barra_progresso.setValue(i);
                    if(barra_progresso.getValue()<= 40)
                    {
                        lbl_mensagem.setText("Carregando Banco de Dados");
                    }else if (barra_progresso.getValue() <= 70)
                    {
                        lbl_mensagem.setText("Carregando Interface Gráfica");
                    }else if(barra_progresso.getValue() <= 90){
                        lbl_mensagem.setText("Carregando Sistema");
                    } else {
                        lbl_mensagem.setText("Tudo Pronto!");
                        btn_ir.setVisible(true);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(frm_Load.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
            
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_progresso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barra_progresso = new javax.swing.JProgressBar();
        lbl_mensagem = new javax.swing.JLabel();
        btn_ir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 436));
        getContentPane().setLayout(null);
        getContentPane().add(lbl_progresso);
        lbl_progresso.setBounds(10, 453, 33, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/burguer.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 500, 370);

        barra_progresso.setName(""); // NOI18N
        barra_progresso.setStringPainted(true);
        getContentPane().add(barra_progresso);
        barra_progresso.setBounds(0, 360, 500, 20);
        getContentPane().add(lbl_mensagem);
        lbl_mensagem.setBounds(20, 380, 450, 14);

        btn_ir.setText("OK!");
        btn_ir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_irActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ir);
        btn_ir.setBounds(430, 380, 51, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_irActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_irActionPerformed
        this.dispose();
        frm_Principal principal = new frm_Principal();
        principal.setVisible(true);  
    }//GEN-LAST:event_btn_irActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          try { 
 UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");

 } catch (ClassNotFoundException ex) { 

 java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) { 

  java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 

} catch (IllegalAccessException ex) { 

java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 

} catch (javax.swing.UnsupportedLookAndFeelException ex) { java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra_progresso;
    private javax.swing.JButton btn_ir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_mensagem;
    private javax.swing.JLabel lbl_progresso;
    // End of variables declaration//GEN-END:variables
}
