/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CEP.ViaCEP;
import CEP.ViaCEPException;
import bean.Cliente;
import bean.Produto;
import dao.ClienteDAO;
import dao.ProdutoDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mendes
 */
public class frm_CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form frm_CadastroCliente
     */
    public frm_CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logo = new javax.swing.JLabel();
        lbl_cadastro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_cep = new javax.swing.JLabel();
        lbl_cidade = new javax.swing.JLabel();
        lbl_bairro = new javax.swing.JLabel();
        lbl_rua = new javax.swing.JLabel();
        lbl_casa = new javax.swing.JLabel();
        lbl_complemento = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        txt_bairro = new javax.swing.JTextField();
        txt_rua = new javax.swing.JTextField();
        txt_numerocasa = new javax.swing.JTextField();
        txt_complemento = new javax.swing.JTextField();
        lbl_nomecliente = new javax.swing.JLabel();
        txt_nome_cliente = new javax.swing.JTextField();
        lbl_telefone = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_cep = new javax.swing.JFormattedTextField();
        txt_telefone = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(645, 376));
        setResizable(false);

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        lbl_cadastro.setText("CADASTRO DE CLIENTE");

        lbl_cep.setText("CEP");

        lbl_cidade.setText("Cidade");

        lbl_bairro.setText("Bairro");

        lbl_rua.setText("Rua");

        lbl_casa.setText("Número");

        lbl_complemento.setText("Comp.");

        txt_cidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cidadeFocusGained(evt);
            }
        });

        txt_numerocasa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_numerocasaFocusGained(evt);
            }
        });

        lbl_nomecliente.setText("Nome ");

        txt_nome_cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nome_clienteFocusGained(evt);
            }
        });
        txt_nome_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_nome_clienteMouseEntered(evt);
            }
        });
        txt_nome_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_clienteActionPerformed(evt);
            }
        });

        lbl_telefone.setText("Telefone ");

        btn_salvar.setText("Cadastrar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cepFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cepFocusLost(evt);
            }
        });

        try {
            txt_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_telefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_telefoneFocusLost(evt);
            }
        });
        txt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rua)
                    .addComponent(lbl_cidade)
                    .addComponent(lbl_cep)
                    .addComponent(lbl_complemento)
                    .addComponent(lbl_casa)
                    .addComponent(lbl_nomecliente)
                    .addComponent(lbl_telefone)
                    .addComponent(lbl_bairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_complemento)
                    .addComponent(txt_cidade)
                    .addComponent(txt_bairro)
                    .addComponent(txt_rua)
                    .addComponent(txt_numerocasa)
                    .addComponent(txt_nome_cliente)
                    .addComponent(txt_cep, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btn_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomecliente)
                    .addComponent(txt_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefone)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cep)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cidade)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rua)
                    .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_casa)
                    .addComponent(txt_numerocasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_complemento))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_logo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lbl_cadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbl_cadastro)
                        .addGap(63, 63, 63)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
try{
                     Cliente c = new Cliente();
                     ClienteDAO dao = new ClienteDAO();
                     c.setNome(txt_nome_cliente.getText());
                   
                     //(13)99670-9814
                     String telefone = txt_telefone.getText().substring(1,3);
                     String telefone1 = txt_telefone.getText().substring(5,9);
                     String telefone2 = txt_telefone.getText().substring(10);
                     System.out.println("\ntel1 = " + telefone + "\ntel2= "+ telefone1 + "\ntel3 = " +telefone2);
                     String telefonesql = telefone + telefone1 + telefone2;
                      c.setTelefone(Integer.parseInt(telefonesql));
                   
                    
                     //c.setTelefone(Integer.parseInt(txt_telefone.getText()));
                     
                     //11310-090
                    String cep = txt_cep.getText().substring(0,5);
                    String cep1 = txt_cep.getText().substring(6);
                    System.out.println("cep=" + cep + "\ncep2= " + cep1);
                    String cepsql = cep + cep1;
                    c.setCep(Integer.parseInt(cepsql));
                    
                    
                     c.setCidade(txt_cidade.getText());
                     c.setBairro(txt_bairro.getText());
                     c.setComplemento(txt_complemento.getText());
                     c.setRua(txt_rua.getText());
                     c.setCasa(Integer.parseInt(txt_numerocasa.getText()));                 
                     dao.create(c);  
}catch(RuntimeException ex)
{
    JOptionPane.showMessageDialog(null, "Sem conexão!", "Falta de conexão", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_nome_clienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nome_clienteFocusGained
 txt_nome_cliente.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {	
            String caracteres=("qwertyuiopasdfghjklçzxcvbnmQWERTYUIOPASDFGHJKLÇZXCVBNM ");        
         if(!caracteres.contains(e.getKeyChar()+"")){
            e.consume();
        }
        }
      });        
    }//GEN-LAST:event_txt_nome_clienteFocusGained

    private void txt_nome_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nome_clienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_clienteMouseEntered

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
   this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txt_cidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cidadeFocusGained
        txt_cidade.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {	
            String caracteres=("qwertyuiopasdfghjklçzxcvbnmQWERTYUIOPASDFGHJKLÇZXCVBNM ");        
         if(!caracteres.contains(e.getKeyChar()+"")){
            e.consume();
        }
        }
      }); 
    }//GEN-LAST:event_txt_cidadeFocusGained

    private void txt_numerocasaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_numerocasaFocusGained
       txt_numerocasa.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {	
            String caracteres=("1234567890");        
         if(!caracteres.contains(e.getKeyChar()+"")){
            e.consume();
        }
        }
      }); 
    }//GEN-LAST:event_txt_numerocasaFocusGained

    private void txt_cepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cepFocusGained
        txt_cep.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {	
            String caracteres=("1234567890");        
         if(!caracteres.contains(e.getKeyChar()+"")){
            e.consume();
        }
        }
      }); 
    }//GEN-LAST:event_txt_cepFocusGained

    private void txt_nome_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_clienteActionPerformed

    private void txt_cepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cepFocusLost
      ViaCEP viacep = new ViaCEP();
        
        try {
            viacep.buscar(txt_cep.getText());
            txt_cidade.setText(viacep.getLocalidade());
            txt_bairro.setText(viacep.getBairro());
            txt_rua.setText(viacep.getLogradouro());
            
        } catch (ViaCEPException ex) {
            JOptionPane.showMessageDialog(null, "CEP Inválido", "ERRO CEP", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_cepFocusLost

    private void txt_telefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telefoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneFocusGained

    private void txt_telefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telefoneFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneFocusLost

    private void txt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_bairro;
    private javax.swing.JLabel lbl_cadastro;
    private javax.swing.JLabel lbl_casa;
    private javax.swing.JLabel lbl_cep;
    private javax.swing.JLabel lbl_cidade;
    private javax.swing.JLabel lbl_complemento;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nomecliente;
    private javax.swing.JLabel lbl_rua;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JFormattedTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_complemento;
    private javax.swing.JTextField txt_nome_cliente;
    private javax.swing.JTextField txt_numerocasa;
    private javax.swing.JTextField txt_rua;
    private javax.swing.JFormattedTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
