/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Usuario;
import connection.ConnectionFactory;
import dao.UsuarioDAO;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static view.frm_CadastroLogin.usuario;
import view.frm_CadastrarLanche;
import view.frm_CadastrarBebida;
import view.frm_CadastrarVariado;

/**
 *
 * @author Mendes
 */
public class frm_Principal extends javax.swing.JFrame {
    String bemvindo = "Bem Vindo: ";
    /**
     * Creates new form frm_Principal
     */
    public frm_Principal() {
         Connection con = ConnectionFactory.getConnection();      
          String sql = "select * from tb_usuario where nm_usuario = \"" + usuario + "\""; 
     try{
        
          PreparedStatement stmt = con.prepareStatement(sql);
          ResultSet rs = stmt.executeQuery();
          lbl_bemvindo.setText(String.valueOf(rs.getString("nm_usuario")));
          
          
          System.out.println("sql" + sql);
          System.out.println("rs" + rs);
          
     }catch(Exception e)
     {
         System.out.println("erro" + e);
         
     }
        
       initComponents();
       setExtendedState(MAXIMIZED_BOTH);
       lbl_bemvindo.setText(bemvindo + usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        btn_lanche = new javax.swing.JButton();
        btn_bebida = new javax.swing.JButton();
        btn_variado = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        btn_motoboy = new javax.swing.JButton();
        lbl_bemvindo = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_pedidos = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        btn_recibo = new javax.swing.JButton();
        btn_pedido = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_adicionar = new javax.swing.JMenu();
        mni_lanche = new javax.swing.JMenuItem();
        mni_bebida = new javax.swing.JMenuItem();
        mni_variado = new javax.swing.JMenuItem();
        mni_cliente = new javax.swing.JMenuItem();
        mni_motoboy = new javax.swing.JMenuItem();
        jmn_sair = new javax.swing.JMenu();
        mn_sair = new javax.swing.JMenuItem();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(1000, 760));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 700));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btn_lanche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/burguer1.png"))); // NOI18N
        btn_lanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lancheActionPerformed(evt);
            }
        });

        btn_bebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drink.png"))); // NOI18N
        btn_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bebidaActionPerformed(evt);
            }
        });

        btn_variado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fries.png"))); // NOI18N
        btn_variado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_variadoActionPerformed(evt);
            }
        });

        btn_cliente.setText("CLIENTES");
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });

        btn_motoboy.setText("MOTOBOY");

        lbl_bemvindo.setText("Bem vindo");

        lbl_total.setText("Total de pedidos:");

        lbl_pedidos.setText("0");

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        btn_recibo.setText("Emitir Recibo");
        btn_recibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reciboActionPerformed(evt);
            }
        });

        btn_pedido.setText("PEDIDO");
        btn_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedidoActionPerformed(evt);
            }
        });

        mn_adicionar.setText("Adicionar");

        mni_lanche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/somarlanche.png"))); // NOI18N
        mni_lanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_lancheActionPerformed(evt);
            }
        });
        mn_adicionar.add(mni_lanche);

        mni_bebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/somardrink.png"))); // NOI18N
        mni_bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_bebidaActionPerformed(evt);
            }
        });
        mn_adicionar.add(mni_bebida);

        mni_variado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/somarvariado.png"))); // NOI18N
        mni_variado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_variadoActionPerformed(evt);
            }
        });
        mn_adicionar.add(mni_variado);

        mni_cliente.setText("Cliente");
        mn_adicionar.add(mni_cliente);

        mni_motoboy.setText("Motoboy");
        mn_adicionar.add(mni_motoboy);

        jMenuBar1.add(mn_adicionar);

        jmn_sair.setText("Sistema");
        jmn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmn_sairActionPerformed(evt);
            }
        });

        mn_sair.setText("Sair");
        mn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_sairActionPerformed(evt);
            }
        });
        jmn_sair.add(mn_sair);

        jMenuBar1.add(jmn_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(620, 620, 620)
                        .addComponent(lbl_total)
                        .addGap(7, 7, 7)
                        .addComponent(lbl_pedidos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_lanche)
                            .addComponent(btn_variado)
                            .addComponent(btn_bebida))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(lbl_bemvindo))
                                    .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_motoboy)
                            .addComponent(btn_recibo)
                            .addComponent(btn_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbl_bemvindo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_lanche)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_motoboy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_bebida)
                    .addComponent(btn_pedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_recibo)
                    .addComponent(btn_variado))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_total)
                    .addComponent(lbl_pedidos)))
        );

        setSize(new java.awt.Dimension(684, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lancheActionPerformed
       // this.setEnabled(false);
      
    
    }//GEN-LAST:event_btn_lancheActionPerformed

    private void btn_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bebidaActionPerformed
      
         //this.setEnabled(false);
         
    }//GEN-LAST:event_btn_bebidaActionPerformed

    private void btn_variadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_variadoActionPerformed
     
        //this.setEnabled(false);
    }//GEN-LAST:event_btn_variadoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    
    }//GEN-LAST:event_formFocusGained

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
        frm_CadastroCliente cliente = new frm_CadastroCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btn_clienteActionPerformed

    private void mni_bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_bebidaActionPerformed
         frm_CadastrarBebida bebida = new frm_CadastrarBebida();
        bebida.setVisible(true);
      
    }//GEN-LAST:event_mni_bebidaActionPerformed

    private void mni_variadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_variadoActionPerformed
         frm_CadastrarVariado variado = new frm_CadastrarVariado();
        variado.setVisible(true);
      
    }//GEN-LAST:event_mni_variadoActionPerformed

    private void btn_reciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reciboActionPerformed
    frm_Conta conta = new frm_Conta();
    conta.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_reciboActionPerformed

    private void btn_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedidoActionPerformed
        frm_Pedido pedido = new frm_Pedido();
        pedido.setVisible(true);
        
    }//GEN-LAST:event_btn_pedidoActionPerformed

    private void jmn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmn_sairActionPerformed
       
    }//GEN-LAST:event_jmn_sairActionPerformed

    private void mn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_sairActionPerformed
       int sair = JOptionPane.showConfirmDialog(null, "Deseja Sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION)
        { 
            this.dispose();
           // System.exit(0);
            frm_Login login = new frm_Login();
            login.setVisible(true);
         }     
    }//GEN-LAST:event_mn_sairActionPerformed

    private void mni_lancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_lancheActionPerformed

        frm_CadastrarLanche lanche = new frm_CadastrarLanche();
        
   //     bebida.setVisible(false);
     //   variado.setVisible(false);

     
       
    }//GEN-LAST:event_mni_lancheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try { 
 UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");

 } catch (ClassNotFoundException ex) { 

 java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) { 

  java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 

} catch (IllegalAccessException ex) { 

java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 

} catch (javax.swing.UnsupportedLookAndFeelException ex) { java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bebida;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_lanche;
    private javax.swing.JButton btn_motoboy;
    private javax.swing.JButton btn_pedido;
    private javax.swing.JButton btn_recibo;
    private javax.swing.JButton btn_variado;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmn_sair;
    private java.awt.Label label1;
    private javax.swing.JLabel lbl_bemvindo;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_pedidos;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JMenu mn_adicionar;
    private javax.swing.JMenuItem mn_sair;
    private javax.swing.JMenuItem mni_bebida;
    private javax.swing.JMenuItem mni_cliente;
    private javax.swing.JMenuItem mni_lanche;
    private javax.swing.JMenuItem mni_motoboy;
    private javax.swing.JMenuItem mni_variado;
    // End of variables declaration//GEN-END:variables

   void setUndecorated() {
       throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   }
}
